/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_Allowed_PNI_NPN_Item_H_
#define	_Allowed_PNI_NPN_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNIdentity.h"
#include <NativeEnumerated.h>
#include "Allowed-CAG-List-per-PLMN.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Allowed_PNI_NPN_Item__pNI_NPN_restricted {
	Allowed_PNI_NPN_Item__pNI_NPN_restricted_restricted	= 0,
	Allowed_PNI_NPN_Item__pNI_NPN_restricted_not_restricted	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Allowed_PNI_NPN_Item__pNI_NPN_restricted;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Allowed-PNI-NPN-Item */
typedef struct Allowed_PNI_NPN_Item {
	PLMNIdentity_t	 pLMNIdentity;
	long	 pNI_NPN_restricted;
	Allowed_CAG_List_per_PLMN_t	 allowed_CAG_List_per_PLMN;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Allowed_PNI_NPN_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_pNI_NPN_restricted_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Allowed_PNI_NPN_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_Allowed_PNI_NPN_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_Allowed_PNI_NPN_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _Allowed_PNI_NPN_Item_H_ */
#include <asn_internal.h>
