/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_BluetoothName_H_
#define	_BluetoothName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BluetoothName */
typedef OCTET_STRING_t	 BluetoothName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BluetoothName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BluetoothName;
asn_struct_free_f BluetoothName_free;
asn_struct_print_f BluetoothName_print;
asn_constr_check_f BluetoothName_constraint;
per_type_decoder_f BluetoothName_decode_uper;
per_type_encoder_f BluetoothName_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BluetoothName_H_ */
#include <asn_internal.h>
