/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_EN_DCSONConfigurationTransfer_H_
#define	_EN_DCSONConfigurationTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EN-DCSONConfigurationTransfer */
typedef OCTET_STRING_t	 EN_DCSONConfigurationTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EN_DCSONConfigurationTransfer;
asn_struct_free_f EN_DCSONConfigurationTransfer_free;
asn_struct_print_f EN_DCSONConfigurationTransfer_print;
asn_constr_check_f EN_DCSONConfigurationTransfer_constraint;
per_type_decoder_f EN_DCSONConfigurationTransfer_decode_uper;
per_type_encoder_f EN_DCSONConfigurationTransfer_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EN_DCSONConfigurationTransfer_H_ */
#include <asn_internal.h>
