/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_EUTRAN_CellReportItem_H_
#define	_EUTRAN_CellReportItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EUTRA-CGI.h"
#include "EUTRAN-CompositeAvailableCapacityGroup.h"
#include "EUTRAN-NumberOfActiveUEs.h"
#include "NGRAN-NoofRRCConnections.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EUTRAN_RadioResourceStatus;
struct ProtocolExtensionContainer;

/* EUTRAN-CellReportItem */
typedef struct EUTRAN_CellReportItem {
	EUTRA_CGI_t	 eCGI;
	EUTRAN_CompositeAvailableCapacityGroup_t	 eUTRAN_CompositeAvailableCapacityGroup;
	EUTRAN_NumberOfActiveUEs_t	*eUTRAN_NumberOfActiveUEs;	/* OPTIONAL */
	NGRAN_NoofRRCConnections_t	*eUTRAN_NoofRRCConnections;	/* OPTIONAL */
	struct EUTRAN_RadioResourceStatus	*eUTRAN_RadioResourceStatus;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_CellReportItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_CellReportItem;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_CellReportItem_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRAN_CellReportItem_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRAN_CellReportItem_H_ */
#include <asn_internal.h>
