/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_EUTRAN_RadioResourceStatus_H_
#define	_EUTRAN_RadioResourceStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* EUTRAN-RadioResourceStatus */
typedef struct EUTRAN_RadioResourceStatus {
	long	 dL_GBR_PRB_usage;
	long	 uL_GBR_PRB_usage;
	long	 dL_non_GBR_PRB_usage;
	long	 uL_non_GBR_PRB_usage;
	long	 dL_Total_PRB_usage;
	long	 uL_Total_PRB_usage;
	long	*dL_scheduling_PDCCH_CCE_usage;	/* OPTIONAL */
	long	*uL_scheduling_PDCCH_CCE_usage;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_RadioResourceStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_RadioResourceStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_RadioResourceStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRAN_RadioResourceStatus_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRAN_RadioResourceStatus_H_ */
#include <asn_internal.h>
