/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_EUTRA_PagingeDRXInformation_H_
#define	_EUTRA_PagingeDRXInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EUTRA-Paging-eDRX-Cycle.h"
#include "EUTRA-Paging-Time-Window.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* EUTRA-PagingeDRXInformation */
typedef struct EUTRA_PagingeDRXInformation {
	EUTRA_Paging_eDRX_Cycle_t	 eUTRA_paging_eDRX_Cycle;
	EUTRA_Paging_Time_Window_t	*eUTRA_paging_Time_Window;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRA_PagingeDRXInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRA_PagingeDRXInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRA_PagingeDRXInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRA_PagingeDRXInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRA_PagingeDRXInformation_H_ */
#include <asn_internal.h>
