/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_EventL1LoggedMDTConfig_H_
#define	_EventL1LoggedMDTConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasurementThresholdL1LoggedMDT.h"
#include "Hysteresis.h"
#include "TimeToTrigger.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* EventL1LoggedMDTConfig */
typedef struct EventL1LoggedMDTConfig {
	MeasurementThresholdL1LoggedMDT_t	 l1Threshold;
	Hysteresis_t	 hysteresis;
	TimeToTrigger_t	 timeToTrigger;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventL1LoggedMDTConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventL1LoggedMDTConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_EventL1LoggedMDTConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_EventL1LoggedMDTConfig_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _EventL1LoggedMDTConfig_H_ */
#include <asn_internal.h>
