/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_ExtendedRNC_ID_H_
#define	_ExtendedRNC_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedRNC-ID */
typedef long	 ExtendedRNC_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExtendedRNC_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExtendedRNC_ID;
asn_struct_free_f ExtendedRNC_ID_free;
asn_struct_print_f ExtendedRNC_ID_print;
asn_constr_check_f ExtendedRNC_ID_constraint;
per_type_decoder_f ExtendedRNC_ID_decode_uper;
per_type_encoder_f ExtendedRNC_ID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedRNC_ID_H_ */
#include <asn_internal.h>
