/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_HOReport_H_
#define	_HOReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "Cause.h"
#include "NGRAN-CGI.h"
#include <BIT_STRING.h>
#include "MobilityInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HOReport__handoverReportType {
	HOReport__handoverReportType_ho_too_early	= 0,
	HOReport__handoverReportType_ho_to_wrong_cell	= 1,
	HOReport__handoverReportType_intersystem_ping_pong	= 2
	/*
	 * Enumeration is extensible
	 */
} e_HOReport__handoverReportType;

/* Forward declarations */
struct NGRAN_CGI;
struct EUTRA_CGI;
struct UERLFReportContainer;
struct ProtocolExtensionContainer;

/* HOReport */
typedef struct HOReport {
	long	 handoverReportType;
	Cause_t	 handoverCause;
	NGRAN_CGI_t	 sourcecellCGI;
	NGRAN_CGI_t	 targetcellCGI;
	struct NGRAN_CGI	*reestablishmentcellCGI;	/* OPTIONAL */
	BIT_STRING_t	*sourcecellC_RNTI;	/* OPTIONAL */
	struct EUTRA_CGI	*targetcellinE_UTRAN;	/* OPTIONAL */
	MobilityInformation_t	*mobilityInformation;	/* OPTIONAL */
	struct UERLFReportContainer	*uERLFReportContainer;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HOReport_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverReportType_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_HOReport;
extern asn_SEQUENCE_specifics_t asn_SPC_HOReport_specs_1;
extern asn_TYPE_member_t asn_MBR_HOReport_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _HOReport_H_ */
#include <asn_internal.h>
