/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_IntersystemSONInformation_H_
#define	_IntersystemSONInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IntersystemSONInformation_PR {
	IntersystemSONInformation_PR_NOTHING,	/* No components present */
	IntersystemSONInformation_PR_intersystemSONInformationReport,
	IntersystemSONInformation_PR_choice_Extensions
} IntersystemSONInformation_PR;

/* Forward declarations */
struct IntersystemSONInformationReport;
struct ProtocolIE_SingleContainer;

/* IntersystemSONInformation */
typedef struct IntersystemSONInformation {
	IntersystemSONInformation_PR present;
	union IntersystemSONInformation_u {
		struct IntersystemSONInformationReport	*intersystemSONInformationReport;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersystemSONInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersystemSONInformation;
extern asn_CHOICE_specifics_t asn_SPC_IntersystemSONInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersystemSONInformation_1[2];
extern asn_per_constraints_t asn_PER_type_IntersystemSONInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersystemSONInformation_H_ */
#include <asn_internal.h>
