/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_LoggingInterval_H_
#define	_LoggingInterval_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoggingInterval {
	LoggingInterval_ms320	= 0,
	LoggingInterval_ms640	= 1,
	LoggingInterval_ms1280	= 2,
	LoggingInterval_ms2560	= 3,
	LoggingInterval_ms5120	= 4,
	LoggingInterval_ms10240	= 5,
	LoggingInterval_ms20480	= 6,
	LoggingInterval_ms30720	= 7,
	LoggingInterval_ms40960	= 8,
	LoggingInterval_ms61440	= 9,
	LoggingInterval_infinity	= 10
	/*
	 * Enumeration is extensible
	 */
} e_LoggingInterval;

/* LoggingInterval */
typedef long	 LoggingInterval_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LoggingInterval_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LoggingInterval;
extern const asn_INTEGER_specifics_t asn_SPC_LoggingInterval_specs_1;
asn_struct_free_f LoggingInterval_free;
asn_struct_print_f LoggingInterval_print;
asn_constr_check_f LoggingInterval_constraint;
per_type_decoder_f LoggingInterval_decode_uper;
per_type_encoder_f LoggingInterval_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoggingInterval_H_ */
#include <asn_internal.h>
