/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_LoggedMDTTrigger_H_
#define	_LoggedMDTTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoggedMDTTrigger_PR {
	LoggedMDTTrigger_PR_NOTHING,	/* No components present */
	LoggedMDTTrigger_PR_periodical,
	LoggedMDTTrigger_PR_eventTrigger,
	LoggedMDTTrigger_PR_choice_Extensions
} LoggedMDTTrigger_PR;

/* Forward declarations */
struct EventTrigger;
struct ProtocolIE_SingleContainer;

/* LoggedMDTTrigger */
typedef struct LoggedMDTTrigger {
	LoggedMDTTrigger_PR present;
	union LoggedMDTTrigger_u {
		NULL_t	 periodical;
		struct EventTrigger	*eventTrigger;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoggedMDTTrigger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoggedMDTTrigger;
extern asn_CHOICE_specifics_t asn_SPC_LoggedMDTTrigger_specs_1;
extern asn_TYPE_member_t asn_MBR_LoggedMDTTrigger_1[3];
extern asn_per_constraints_t asn_PER_type_LoggedMDTTrigger_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LoggedMDTTrigger_H_ */
#include <asn_internal.h>
