/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_M1Configuration_H_
#define	_M1Configuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "M1ReportingTrigger.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct M1ThresholdEventA2;
struct M1PeriodicReporting;
struct ProtocolExtensionContainer;

/* M1Configuration */
typedef struct M1Configuration {
	M1ReportingTrigger_t	 m1reportingTrigger;
	struct M1ThresholdEventA2	*m1thresholdEventA2;	/* OPTIONAL */
	struct M1PeriodicReporting	*m1periodicReporting;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M1Configuration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M1Configuration;
extern asn_SEQUENCE_specifics_t asn_SPC_M1Configuration_specs_1;
extern asn_TYPE_member_t asn_MBR_M1Configuration_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _M1Configuration_H_ */
#include <asn_internal.h>
