/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_M4period_H_
#define	_M4period_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum M4period {
	M4period_ms1024	= 0,
	M4period_ms2048	= 1,
	M4period_ms5120	= 2,
	M4period_ms10240	= 3,
	M4period_min1	= 4
	/*
	 * Enumeration is extensible
	 */
} e_M4period;

/* M4period */
typedef long	 M4period_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_M4period_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_M4period;
extern const asn_INTEGER_specifics_t asn_SPC_M4period_specs_1;
asn_struct_free_f M4period_free;
asn_struct_print_f M4period_print;
asn_constr_check_f M4period_constraint;
per_type_decoder_f M4period_decode_uper;
per_type_encoder_f M4period_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _M4period_H_ */
#include <asn_internal.h>
