/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_M4ReportAmountMDT_H_
#define	_M4ReportAmountMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum M4ReportAmountMDT {
	M4ReportAmountMDT_r1	= 0,
	M4ReportAmountMDT_r2	= 1,
	M4ReportAmountMDT_r4	= 2,
	M4ReportAmountMDT_r8	= 3,
	M4ReportAmountMDT_r16	= 4,
	M4ReportAmountMDT_r32	= 5,
	M4ReportAmountMDT_r64	= 6,
	M4ReportAmountMDT_infinity	= 7
	/*
	 * Enumeration is extensible
	 */
} e_M4ReportAmountMDT;

/* M4ReportAmountMDT */
typedef long	 M4ReportAmountMDT_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_M4ReportAmountMDT_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_M4ReportAmountMDT;
extern const asn_INTEGER_specifics_t asn_SPC_M4ReportAmountMDT_specs_1;
asn_struct_free_f M4ReportAmountMDT_free;
asn_struct_print_f M4ReportAmountMDT_print;
asn_constr_check_f M4ReportAmountMDT_constraint;
per_type_decoder_f M4ReportAmountMDT_decode_uper;
per_type_encoder_f M4ReportAmountMDT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _M4ReportAmountMDT_H_ */
#include <asn_internal.h>
