/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MBS_DataForwardingResponseMRBItem_H_
#define	_MBS_DataForwardingResponseMRBItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MRB-ID.h"
#include "UPTransportLayerInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MRB_ProgressInformation;
struct ProtocolExtensionContainer;

/* MBS-DataForwardingResponseMRBItem */
typedef struct MBS_DataForwardingResponseMRBItem {
	MRB_ID_t	 mRB_ID;
	UPTransportLayerInformation_t	 dL_Forwarding_UPTNLInformation;
	struct MRB_ProgressInformation	*mRB_ProgressInformation;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_DataForwardingResponseMRBItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_DataForwardingResponseMRBItem;
extern asn_SEQUENCE_specifics_t asn_SPC_MBS_DataForwardingResponseMRBItem_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_DataForwardingResponseMRBItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MBS_DataForwardingResponseMRBItem_H_ */
#include <asn_internal.h>
