/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MBSSessionToReleaseItem_H_
#define	_MBSSessionToReleaseItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MBS-SessionID.h"
#include "Cause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* MBSSessionToReleaseItem */
typedef struct MBSSessionToReleaseItem {
	MBS_SessionID_t	 mBS_SessionID;
	Cause_t	 cause;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSSessionToReleaseItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBSSessionToReleaseItem;
extern asn_SEQUENCE_specifics_t asn_SPC_MBSSessionToReleaseItem_specs_1;
extern asn_TYPE_member_t asn_MBR_MBSSessionToReleaseItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MBSSessionToReleaseItem_H_ */
#include <asn_internal.h>
