/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MDT_Configuration_NR_H_
#define	_MDT_Configuration_NR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MDT-Activation.h"
#include "AreaScopeOfMDT-NR.h"
#include "MDTModeNr.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MDTPLMNList;
struct ProtocolExtensionContainer;

/* MDT-Configuration-NR */
typedef struct MDT_Configuration_NR {
	MDT_Activation_t	 mdt_Activation;
	AreaScopeOfMDT_NR_t	 areaScopeOfMDT;
	MDTModeNr_t	 mDTModeNr;
	struct MDTPLMNList	*signallingBasedMDTPLMNList;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MDT_Configuration_NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MDT_Configuration_NR;
extern asn_SEQUENCE_specifics_t asn_SPC_MDT_Configuration_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_MDT_Configuration_NR_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _MDT_Configuration_NR_H_ */
#include <asn_internal.h>
