/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NB_IoT_Paging_eDRXCycle_H_
#define	_NB_IoT_Paging_eDRXCycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NB_IoT_Paging_eDRXCycle {
	NB_IoT_Paging_eDRXCycle_hf2	= 0,
	NB_IoT_Paging_eDRXCycle_hf4	= 1,
	NB_IoT_Paging_eDRXCycle_hf6	= 2,
	NB_IoT_Paging_eDRXCycle_hf8	= 3,
	NB_IoT_Paging_eDRXCycle_hf10	= 4,
	NB_IoT_Paging_eDRXCycle_hf12	= 5,
	NB_IoT_Paging_eDRXCycle_hf14	= 6,
	NB_IoT_Paging_eDRXCycle_hf16	= 7,
	NB_IoT_Paging_eDRXCycle_hf32	= 8,
	NB_IoT_Paging_eDRXCycle_hf64	= 9,
	NB_IoT_Paging_eDRXCycle_hf128	= 10,
	NB_IoT_Paging_eDRXCycle_hf256	= 11,
	NB_IoT_Paging_eDRXCycle_hf512	= 12,
	NB_IoT_Paging_eDRXCycle_hf1024	= 13
	/*
	 * Enumeration is extensible
	 */
} e_NB_IoT_Paging_eDRXCycle;

/* NB-IoT-Paging-eDRXCycle */
typedef long	 NB_IoT_Paging_eDRXCycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NB_IoT_Paging_eDRXCycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NB_IoT_Paging_eDRXCycle;
extern const asn_INTEGER_specifics_t asn_SPC_NB_IoT_Paging_eDRXCycle_specs_1;
asn_struct_free_f NB_IoT_Paging_eDRXCycle_free;
asn_struct_print_f NB_IoT_Paging_eDRXCycle_print;
asn_constr_check_f NB_IoT_Paging_eDRXCycle_constraint;
per_type_decoder_f NB_IoT_Paging_eDRXCycle_decode_uper;
per_type_encoder_f NB_IoT_Paging_eDRXCycle_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NB_IoT_Paging_eDRXCycle_H_ */
#include <asn_internal.h>
