/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NGRAN_CellReportItem_H_
#define	_NGRAN_CellReportItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGRAN-CGI.h"
#include "EUTRAN-CompositeAvailableCapacityGroup.h"
#include "NGRAN-NumberOfActiveUEs.h"
#include "NGRAN-NoofRRCConnections.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGRAN_RadioResourceStatus;
struct ProtocolExtensionContainer;

/* NGRAN-CellReportItem */
typedef struct NGRAN_CellReportItem {
	NGRAN_CGI_t	 nGRAN_CGI;
	EUTRAN_CompositeAvailableCapacityGroup_t	 nGRAN_CompositeAvailableCapacityGroup;
	NGRAN_NumberOfActiveUEs_t	*nGRAN_NumberOfActiveUEs;	/* OPTIONAL */
	NGRAN_NoofRRCConnections_t	*nGRAN_NoofRRCConnections;	/* OPTIONAL */
	struct NGRAN_RadioResourceStatus	*nGRAN_RadioResourceStatus;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGRAN_CellReportItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGRAN_CellReportItem;
extern asn_SEQUENCE_specifics_t asn_SPC_NGRAN_CellReportItem_specs_1;
extern asn_TYPE_member_t asn_MBR_NGRAN_CellReportItem_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NGRAN_CellReportItem_H_ */
#include <asn_internal.h>
