/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NPN_PagingAssistanceInformation_H_
#define	_NPN_PagingAssistanceInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPN_PagingAssistanceInformation_PR {
	NPN_PagingAssistanceInformation_PR_NOTHING,	/* No components present */
	NPN_PagingAssistanceInformation_PR_pNI_NPN_PagingAssistance,
	NPN_PagingAssistanceInformation_PR_choice_Extensions
} NPN_PagingAssistanceInformation_PR;

/* Forward declarations */
struct Allowed_PNI_NPN_List;
struct ProtocolIE_SingleContainer;

/* NPN-PagingAssistanceInformation */
typedef struct NPN_PagingAssistanceInformation {
	NPN_PagingAssistanceInformation_PR present;
	union NPN_PagingAssistanceInformation_u {
		struct Allowed_PNI_NPN_List	*pNI_NPN_PagingAssistance;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPN_PagingAssistanceInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPN_PagingAssistanceInformation;
extern asn_CHOICE_specifics_t asn_SPC_NPN_PagingAssistanceInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NPN_PagingAssistanceInformation_1[2];
extern asn_per_constraints_t asn_PER_type_NPN_PagingAssistanceInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NPN_PagingAssistanceInformation_H_ */
#include <asn_internal.h>
