/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NPN_MobilityInformation_H_
#define	_NPN_MobilityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPN_MobilityInformation_PR {
	NPN_MobilityInformation_PR_NOTHING,	/* No components present */
	NPN_MobilityInformation_PR_sNPN_MobilityInformation,
	NPN_MobilityInformation_PR_pNI_NPN_MobilityInformation,
	NPN_MobilityInformation_PR_choice_Extensions
} NPN_MobilityInformation_PR;

/* Forward declarations */
struct SNPN_MobilityInformation;
struct PNI_NPN_MobilityInformation;
struct ProtocolIE_SingleContainer;

/* NPN-MobilityInformation */
typedef struct NPN_MobilityInformation {
	NPN_MobilityInformation_PR present;
	union NPN_MobilityInformation_u {
		struct SNPN_MobilityInformation	*sNPN_MobilityInformation;
		struct PNI_NPN_MobilityInformation	*pNI_NPN_MobilityInformation;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPN_MobilityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPN_MobilityInformation;
extern asn_CHOICE_specifics_t asn_SPC_NPN_MobilityInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NPN_MobilityInformation_1[3];
extern asn_per_constraints_t asn_PER_type_NPN_MobilityInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NPN_MobilityInformation_H_ */
#include <asn_internal.h>
