/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NR_Paging_Time_Window_H_
#define	_NR_Paging_Time_Window_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_Paging_Time_Window {
	NR_Paging_Time_Window_s1	= 0,
	NR_Paging_Time_Window_s2	= 1,
	NR_Paging_Time_Window_s3	= 2,
	NR_Paging_Time_Window_s4	= 3,
	NR_Paging_Time_Window_s5	= 4,
	NR_Paging_Time_Window_s6	= 5,
	NR_Paging_Time_Window_s7	= 6,
	NR_Paging_Time_Window_s8	= 7,
	NR_Paging_Time_Window_s9	= 8,
	NR_Paging_Time_Window_s10	= 9,
	NR_Paging_Time_Window_s11	= 10,
	NR_Paging_Time_Window_s12	= 11,
	NR_Paging_Time_Window_s13	= 12,
	NR_Paging_Time_Window_s14	= 13,
	NR_Paging_Time_Window_s15	= 14,
	NR_Paging_Time_Window_s16	= 15,
	/*
	 * Enumeration is extensible
	 */
	NR_Paging_Time_Window_s17	= 16,
	NR_Paging_Time_Window_s18	= 17,
	NR_Paging_Time_Window_s19	= 18,
	NR_Paging_Time_Window_s20	= 19,
	NR_Paging_Time_Window_s21	= 20,
	NR_Paging_Time_Window_s22	= 21,
	NR_Paging_Time_Window_s23	= 22,
	NR_Paging_Time_Window_s24	= 23,
	NR_Paging_Time_Window_s25	= 24,
	NR_Paging_Time_Window_s26	= 25,
	NR_Paging_Time_Window_s27	= 26,
	NR_Paging_Time_Window_s28	= 27,
	NR_Paging_Time_Window_s29	= 28,
	NR_Paging_Time_Window_s30	= 29,
	NR_Paging_Time_Window_s31	= 30,
	NR_Paging_Time_Window_s32	= 31
} e_NR_Paging_Time_Window;

/* NR-Paging-Time-Window */
typedef long	 NR_Paging_Time_Window_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NR_Paging_Time_Window_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NR_Paging_Time_Window;
extern const asn_INTEGER_specifics_t asn_SPC_NR_Paging_Time_Window_specs_1;
asn_struct_free_f NR_Paging_Time_Window_free;
asn_struct_print_f NR_Paging_Time_Window_print;
asn_constr_check_f NR_Paging_Time_Window_constraint;
per_type_decoder_f NR_Paging_Time_Window_decode_uper;
per_type_encoder_f NR_Paging_Time_Window_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NR_Paging_Time_Window_H_ */
#include <asn_internal.h>
