/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-PDU-Contents"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_PathSwitchRequest_H_
#define	_PathSwitchRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathSwitchRequest */
typedef struct PathSwitchRequest {
	ProtocolIE_Container_11854P35_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathSwitchRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathSwitchRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_PathSwitchRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_PathSwitchRequest_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PathSwitchRequest_H_ */
#include <asn_internal.h>
