/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_ResourceStatusReportingSystem_H_
#define	_ResourceStatusReportingSystem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ResourceStatusReportingSystem_PR {
	ResourceStatusReportingSystem_PR_NOTHING,	/* No components present */
	ResourceStatusReportingSystem_PR_eUTRAN_ReportingStatus,
	ResourceStatusReportingSystem_PR_nGRAN_ReportingStatus,
	ResourceStatusReportingSystem_PR_choice_Extensions
} ResourceStatusReportingSystem_PR;

/* Forward declarations */
struct EUTRAN_ReportingStatusIEs;
struct NGRAN_ReportingStatusIEs;
struct ProtocolIE_SingleContainer;

/* ResourceStatusReportingSystem */
typedef struct ResourceStatusReportingSystem {
	ResourceStatusReportingSystem_PR present;
	union ResourceStatusReportingSystem_u {
		struct EUTRAN_ReportingStatusIEs	*eUTRAN_ReportingStatus;
		struct NGRAN_ReportingStatusIEs	*nGRAN_ReportingStatus;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceStatusReportingSystem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceStatusReportingSystem;
extern asn_CHOICE_specifics_t asn_SPC_ResourceStatusReportingSystem_specs_1;
extern asn_TYPE_member_t asn_MBR_ResourceStatusReportingSystem_1[3];
extern asn_per_constraints_t asn_PER_type_ResourceStatusReportingSystem_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ResourceStatusReportingSystem_H_ */
#include <asn_internal.h>
