/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_SgNB_UE_X2AP_ID_H_
#define	_SgNB_UE_X2AP_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SgNB-UE-X2AP-ID */
typedef unsigned long	 SgNB_UE_X2AP_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SgNB_UE_X2AP_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SgNB_UE_X2AP_ID;
extern const asn_INTEGER_specifics_t asn_SPC_SgNB_UE_X2AP_ID_specs_1;
asn_struct_free_f SgNB_UE_X2AP_ID_free;
asn_struct_print_f SgNB_UE_X2AP_ID_print;
asn_constr_check_f SgNB_UE_X2AP_ID_constraint;
per_type_decoder_f SgNB_UE_X2AP_ID_decode_uper;
per_type_encoder_f SgNB_UE_X2AP_ID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SgNB_UE_X2AP_ID_H_ */
#include <asn_internal.h>
