/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_SourceNodeID_H_
#define	_SourceNodeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SourceNodeID_PR {
	SourceNodeID_PR_NOTHING,	/* No components present */
	SourceNodeID_PR_sourceengNB_ID,
	SourceNodeID_PR_choice_Extensions
} SourceNodeID_PR;

/* Forward declarations */
struct GlobalGNB_ID;
struct ProtocolIE_SingleContainer;

/* SourceNodeID */
typedef struct SourceNodeID {
	SourceNodeID_PR present;
	union SourceNodeID_u {
		struct GlobalGNB_ID	*sourceengNB_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SourceNodeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SourceNodeID;
extern asn_CHOICE_specifics_t asn_SPC_SourceNodeID_specs_1;
extern asn_TYPE_member_t asn_MBR_SourceNodeID_1[2];
extern asn_per_constraints_t asn_PER_type_SourceNodeID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SourceNodeID_H_ */
#include <asn_internal.h>
