/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-PDU-Descriptions"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_SuccessfulOutcome_H_
#define	_SuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "AMFConfigurationUpdate.h"
#include "AMFConfigurationUpdateAcknowledge.h"
#include "AMFConfigurationUpdateFailure.h"
#include "BroadcastSessionModificationRequest.h"
#include "BroadcastSessionModificationResponse.h"
#include "BroadcastSessionModificationFailure.h"
#include "BroadcastSessionReleaseRequest.h"
#include "BroadcastSessionReleaseResponse.h"
#include "BroadcastSessionSetupRequest.h"
#include "BroadcastSessionSetupResponse.h"
#include "BroadcastSessionSetupFailure.h"
#include "DistributionSetupRequest.h"
#include "DistributionSetupResponse.h"
#include "DistributionSetupFailure.h"
#include "DistributionReleaseRequest.h"
#include "DistributionReleaseResponse.h"
#include "HandoverCancel.h"
#include "HandoverCancelAcknowledge.h"
#include "HandoverRequired.h"
#include "HandoverCommand.h"
#include "HandoverPreparationFailure.h"
#include "HandoverRequest.h"
#include "HandoverRequestAcknowledge.h"
#include "HandoverFailure.h"
#include "InitialContextSetupRequest.h"
#include "InitialContextSetupResponse.h"
#include "InitialContextSetupFailure.h"
#include "MulticastSessionActivationRequest.h"
#include "MulticastSessionActivationResponse.h"
#include "MulticastSessionActivationFailure.h"
#include "MulticastSessionDeactivationRequest.h"
#include "MulticastSessionDeactivationResponse.h"
#include "MulticastSessionUpdateRequest.h"
#include "MulticastSessionUpdateResponse.h"
#include "MulticastSessionUpdateFailure.h"
#include "NGReset.h"
#include "NGResetAcknowledge.h"
#include "NGSetupRequest.h"
#include "NGSetupResponse.h"
#include "NGSetupFailure.h"
#include "PathSwitchRequest.h"
#include "PathSwitchRequestAcknowledge.h"
#include "PathSwitchRequestFailure.h"
#include "PDUSessionResourceModifyRequest.h"
#include "PDUSessionResourceModifyResponse.h"
#include "PDUSessionResourceModifyIndication.h"
#include "PDUSessionResourceModifyConfirm.h"
#include "PDUSessionResourceReleaseCommand.h"
#include "PDUSessionResourceReleaseResponse.h"
#include "PDUSessionResourceSetupRequest.h"
#include "PDUSessionResourceSetupResponse.h"
#include "PWSCancelRequest.h"
#include "PWSCancelResponse.h"
#include "RANConfigurationUpdate.h"
#include "RANConfigurationUpdateAcknowledge.h"
#include "RANConfigurationUpdateFailure.h"
#include "UEContextModificationRequest.h"
#include "UEContextModificationResponse.h"
#include "UEContextModificationFailure.h"
#include "UEContextReleaseCommand.h"
#include "UEContextReleaseComplete.h"
#include "UEContextResumeRequest.h"
#include "UEContextResumeResponse.h"
#include "UEContextResumeFailure.h"
#include "UEContextSuspendRequest.h"
#include "UEContextSuspendResponse.h"
#include "UEContextSuspendFailure.h"
#include "UERadioCapabilityCheckRequest.h"
#include "UERadioCapabilityCheckResponse.h"
#include "UERadioCapabilityIDMappingRequest.h"
#include "UERadioCapabilityIDMappingResponse.h"
#include "WriteReplaceWarningRequest.h"
#include "WriteReplaceWarningResponse.h"
#include "AMFCPRelocationIndication.h"
#include "AMFStatusIndication.h"
#include "BroadcastSessionReleaseRequired.h"
#include "CellTrafficTrace.h"
#include "ConnectionEstablishmentIndication.h"
#include "DeactivateTrace.h"
#include "DownlinkNASTransport.h"
#include "DownlinkNonUEAssociatedNRPPaTransport.h"
#include "DownlinkRANConfigurationTransfer.h"
#include "DownlinkRANEarlyStatusTransfer.h"
#include "DownlinkRANStatusTransfer.h"
#include "DownlinkRIMInformationTransfer.h"
#include "DownlinkUEAssociatedNRPPaTransport.h"
#include "ErrorIndication.h"
#include "HandoverNotify.h"
#include "HandoverSuccess.h"
#include "InitialUEMessage.h"
#include "LocationReport.h"
#include "LocationReportingControl.h"
#include "LocationReportingFailureIndication.h"
#include "MulticastGroupPaging.h"
#include "NASNonDeliveryIndication.h"
#include "OverloadStart.h"
#include "OverloadStop.h"
#include "Paging.h"
#include "PDUSessionResourceNotify.h"
#include "PrivateMessage.h"
#include "PWSFailureIndication.h"
#include "PWSRestartIndication.h"
#include "RANCPRelocationIndication.h"
#include "RerouteNASRequest.h"
#include "RetrieveUEInformation.h"
#include "RRCInactiveTransitionReport.h"
#include "SecondaryRATDataUsageReport.h"
#include "TraceFailureIndication.h"
#include "TraceStart.h"
#include "UEContextReleaseRequest.h"
#include "UEInformationTransfer.h"
#include "UERadioCapabilityInfoIndication.h"
#include "UETNLABindingReleaseRequest.h"
#include "UplinkNASTransport.h"
#include "UplinkNonUEAssociatedNRPPaTransport.h"
#include "UplinkRANConfigurationTransfer.h"
#include "UplinkRANEarlyStatusTransfer.h"
#include "UplinkRANStatusTransfer.h"
#include "UplinkRIMInformationTransfer.h"
#include "UplinkUEAssociatedNRPPaTransport.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SuccessfulOutcome__value_PR {
	SuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	SuccessfulOutcome__value_PR_AMFConfigurationUpdateAcknowledge,
	SuccessfulOutcome__value_PR_BroadcastSessionModificationResponse,
	SuccessfulOutcome__value_PR_BroadcastSessionReleaseResponse,
	SuccessfulOutcome__value_PR_BroadcastSessionSetupResponse,
	SuccessfulOutcome__value_PR_DistributionSetupResponse,
	SuccessfulOutcome__value_PR_DistributionReleaseResponse,
	SuccessfulOutcome__value_PR_HandoverCancelAcknowledge,
	SuccessfulOutcome__value_PR_HandoverCommand,
	SuccessfulOutcome__value_PR_HandoverRequestAcknowledge,
	SuccessfulOutcome__value_PR_InitialContextSetupResponse,
	SuccessfulOutcome__value_PR_MulticastSessionActivationResponse,
	SuccessfulOutcome__value_PR_MulticastSessionDeactivationResponse,
	SuccessfulOutcome__value_PR_MulticastSessionUpdateResponse,
	SuccessfulOutcome__value_PR_NGResetAcknowledge,
	SuccessfulOutcome__value_PR_NGSetupResponse,
	SuccessfulOutcome__value_PR_PathSwitchRequestAcknowledge,
	SuccessfulOutcome__value_PR_PDUSessionResourceModifyResponse,
	SuccessfulOutcome__value_PR_PDUSessionResourceModifyConfirm,
	SuccessfulOutcome__value_PR_PDUSessionResourceReleaseResponse,
	SuccessfulOutcome__value_PR_PDUSessionResourceSetupResponse,
	SuccessfulOutcome__value_PR_PWSCancelResponse,
	SuccessfulOutcome__value_PR_RANConfigurationUpdateAcknowledge,
	SuccessfulOutcome__value_PR_UEContextModificationResponse,
	SuccessfulOutcome__value_PR_UEContextReleaseComplete,
	SuccessfulOutcome__value_PR_UEContextResumeResponse,
	SuccessfulOutcome__value_PR_UEContextSuspendResponse,
	SuccessfulOutcome__value_PR_UERadioCapabilityCheckResponse,
	SuccessfulOutcome__value_PR_UERadioCapabilityIDMappingResponse,
	SuccessfulOutcome__value_PR_WriteReplaceWarningResponse
} SuccessfulOutcome__value_PR;

/* SuccessfulOutcome */
typedef struct SuccessfulOutcome {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct SuccessfulOutcome__value {
		SuccessfulOutcome__value_PR present;
		union SuccessfulOutcome__value_u {
			AMFConfigurationUpdateAcknowledge_t	 AMFConfigurationUpdateAcknowledge;
			BroadcastSessionModificationResponse_t	 BroadcastSessionModificationResponse;
			BroadcastSessionReleaseResponse_t	 BroadcastSessionReleaseResponse;
			BroadcastSessionSetupResponse_t	 BroadcastSessionSetupResponse;
			DistributionSetupResponse_t	 DistributionSetupResponse;
			DistributionReleaseResponse_t	 DistributionReleaseResponse;
			HandoverCancelAcknowledge_t	 HandoverCancelAcknowledge;
			HandoverCommand_t	 HandoverCommand;
			HandoverRequestAcknowledge_t	 HandoverRequestAcknowledge;
			InitialContextSetupResponse_t	 InitialContextSetupResponse;
			MulticastSessionActivationResponse_t	 MulticastSessionActivationResponse;
			MulticastSessionDeactivationResponse_t	 MulticastSessionDeactivationResponse;
			MulticastSessionUpdateResponse_t	 MulticastSessionUpdateResponse;
			NGResetAcknowledge_t	 NGResetAcknowledge;
			NGSetupResponse_t	 NGSetupResponse;
			PathSwitchRequestAcknowledge_t	 PathSwitchRequestAcknowledge;
			PDUSessionResourceModifyResponse_t	 PDUSessionResourceModifyResponse;
			PDUSessionResourceModifyConfirm_t	 PDUSessionResourceModifyConfirm;
			PDUSessionResourceReleaseResponse_t	 PDUSessionResourceReleaseResponse;
			PDUSessionResourceSetupResponse_t	 PDUSessionResourceSetupResponse;
			PWSCancelResponse_t	 PWSCancelResponse;
			RANConfigurationUpdateAcknowledge_t	 RANConfigurationUpdateAcknowledge;
			UEContextModificationResponse_t	 UEContextModificationResponse;
			UEContextReleaseComplete_t	 UEContextReleaseComplete;
			UEContextResumeResponse_t	 UEContextResumeResponse;
			UEContextSuspendResponse_t	 UEContextSuspendResponse;
			UERadioCapabilityCheckResponse_t	 UERadioCapabilityCheckResponse;
			UERadioCapabilityIDMappingResponse_t	 UERadioCapabilityIDMappingResponse;
			WriteReplaceWarningResponse_t	 WriteReplaceWarningResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_SuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_SuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SuccessfulOutcome_H_ */
#include <asn_internal.h>
