/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_Threshold_RSRP_H_
#define	_Threshold_RSRP_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Threshold-RSRP */
typedef long	 Threshold_RSRP_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Threshold_RSRP_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Threshold_RSRP;
asn_struct_free_f Threshold_RSRP_free;
asn_struct_print_f Threshold_RSRP_print;
asn_constr_check_f Threshold_RSRP_constraint;
per_type_decoder_f Threshold_RSRP_decode_uper;
per_type_encoder_f Threshold_RSRP_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Threshold_RSRP_H_ */
#include <asn_internal.h>
