/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_TNGF_ID_H_
#define	_TNGF_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TNGF_ID_PR {
	TNGF_ID_PR_NOTHING,	/* No components present */
	TNGF_ID_PR_tNGF_ID,
	TNGF_ID_PR_choice_Extensions
} TNGF_ID_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* TNGF-ID */
typedef struct TNGF_ID {
	TNGF_ID_PR present;
	union TNGF_ID_u {
		BIT_STRING_t	 tNGF_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TNGF_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TNGF_ID;
extern asn_CHOICE_specifics_t asn_SPC_TNGF_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_TNGF_ID_1[2];
extern asn_per_constraints_t asn_PER_type_TNGF_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _TNGF_ID_H_ */
#include <asn_internal.h>
