/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_UE_DifferentiationInfo_H_
#define	_UE_DifferentiationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_DifferentiationInfo__periodicCommunicationIndicator {
	UE_DifferentiationInfo__periodicCommunicationIndicator_periodically	= 0,
	UE_DifferentiationInfo__periodicCommunicationIndicator_ondemand	= 1
	/*
	 * Enumeration is extensible
	 */
} e_UE_DifferentiationInfo__periodicCommunicationIndicator;
typedef enum UE_DifferentiationInfo__stationaryIndication {
	UE_DifferentiationInfo__stationaryIndication_stationary	= 0,
	UE_DifferentiationInfo__stationaryIndication_mobile	= 1
	/*
	 * Enumeration is extensible
	 */
} e_UE_DifferentiationInfo__stationaryIndication;
typedef enum UE_DifferentiationInfo__trafficProfile {
	UE_DifferentiationInfo__trafficProfile_single_packet	= 0,
	UE_DifferentiationInfo__trafficProfile_dual_packets	= 1,
	UE_DifferentiationInfo__trafficProfile_multiple_packets	= 2
	/*
	 * Enumeration is extensible
	 */
} e_UE_DifferentiationInfo__trafficProfile;
typedef enum UE_DifferentiationInfo__batteryIndication {
	UE_DifferentiationInfo__batteryIndication_battery_powered	= 0,
	UE_DifferentiationInfo__batteryIndication_battery_powered_not_rechargeable_or_replaceable	= 1,
	UE_DifferentiationInfo__batteryIndication_not_battery_powered	= 2
	/*
	 * Enumeration is extensible
	 */
} e_UE_DifferentiationInfo__batteryIndication;

/* Forward declarations */
struct ScheduledCommunicationTime;
struct ProtocolExtensionContainer;

/* UE-DifferentiationInfo */
typedef struct UE_DifferentiationInfo {
	long	*periodicCommunicationIndicator;	/* OPTIONAL */
	long	*periodicTime;	/* OPTIONAL */
	struct ScheduledCommunicationTime	*scheduledCommunicationTime;	/* OPTIONAL */
	long	*stationaryIndication;	/* OPTIONAL */
	long	*trafficProfile;	/* OPTIONAL */
	long	*batteryIndication;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_DifferentiationInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_periodicCommunicationIndicator_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_stationaryIndication_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_trafficProfile_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_batteryIndication_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_DifferentiationInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_DifferentiationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_DifferentiationInfo_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _UE_DifferentiationInfo_H_ */
#include <asn_internal.h>
