/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_UEAppLayerMeasConfigInfo_H_
#define	_UEAppLayerMeasConfigInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoEReference.h"
#include "ServiceType.h"
#include "AreaScopeOfQMC.h"
#include "TransportLayerAddress.h"
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEAppLayerMeasConfigInfo__qoEMeasurementStatus {
	UEAppLayerMeasConfigInfo__qoEMeasurementStatus_ongoing	= 0
	/*
	 * Enumeration is extensible
	 */
} e_UEAppLayerMeasConfigInfo__qoEMeasurementStatus;

/* Forward declarations */
struct SliceSupportListQMC;
struct MDT_AlignmentInfo;
struct AvailableRANVisibleQoEMetrics;
struct ProtocolExtensionContainer;

/* UEAppLayerMeasConfigInfo */
typedef struct UEAppLayerMeasConfigInfo {
	QoEReference_t	 qoEReference;
	ServiceType_t	 serviceType;
	AreaScopeOfQMC_t	 areaScopeOfQMC;
	TransportLayerAddress_t	 measCollEntityIPAddress;
	long	*qoEMeasurementStatus;	/* OPTIONAL */
	OCTET_STRING_t	*containerForAppLayerMeasConfig;	/* OPTIONAL */
	long	*measConfigAppLayerID;	/* OPTIONAL */
	struct SliceSupportListQMC	*sliceSupportListQMC;	/* OPTIONAL */
	struct MDT_AlignmentInfo	*mDT_AlignmentInfo;	/* OPTIONAL */
	struct AvailableRANVisibleQoEMetrics	*availableRANVisibleQoEMetrics;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEAppLayerMeasConfigInfo_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_qoEMeasurementStatus_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UEAppLayerMeasConfigInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_UEAppLayerMeasConfigInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_UEAppLayerMeasConfigInfo_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _UEAppLayerMeasConfigInfo_H_ */
#include <asn_internal.h>
