/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_UERLFReportContainer_H_
#define	_UERLFReportContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRUERLFReportContainer.h"
#include "LTEUERLFReportContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UERLFReportContainer_PR {
	UERLFReportContainer_PR_NOTHING,	/* No components present */
	UERLFReportContainer_PR_nR,
	UERLFReportContainer_PR_lTE,
	UERLFReportContainer_PR_choice_Extensions
} UERLFReportContainer_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* UERLFReportContainer */
typedef struct UERLFReportContainer {
	UERLFReportContainer_PR present;
	union UERLFReportContainer_u {
		NRUERLFReportContainer_t	 nR;
		LTEUERLFReportContainer_t	 lTE;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UERLFReportContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UERLFReportContainer;
extern asn_CHOICE_specifics_t asn_SPC_UERLFReportContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_UERLFReportContainer_1[3];
extern asn_per_constraints_t asn_PER_type_UERLFReportContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UERLFReportContainer_H_ */
#include <asn_internal.h>
