/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_AreaScopeOfMDT_NR_H_
#define	_AreaScopeOfMDT_NR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AreaScopeOfMDT_NR_PR {
	AreaScopeOfMDT_NR_PR_NOTHING,	/* No components present */
	AreaScopeOfMDT_NR_PR_cellBased,
	AreaScopeOfMDT_NR_PR_tABased,
	AreaScopeOfMDT_NR_PR_pLMNWide,
	AreaScopeOfMDT_NR_PR_tAIBased,
	AreaScopeOfMDT_NR_PR_choice_Extensions
} AreaScopeOfMDT_NR_PR;

/* Forward declarations */
struct CellBasedMDT_NR;
struct TABasedMDT;
struct TAIBasedMDT;
struct ProtocolIE_SingleContainer;

/* AreaScopeOfMDT-NR */
typedef struct AreaScopeOfMDT_NR {
	AreaScopeOfMDT_NR_PR present;
	union AreaScopeOfMDT_NR_u {
		struct CellBasedMDT_NR	*cellBased;
		struct TABasedMDT	*tABased;
		NULL_t	 pLMNWide;
		struct TAIBasedMDT	*tAIBased;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaScopeOfMDT_NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaScopeOfMDT_NR;
extern asn_CHOICE_specifics_t asn_SPC_AreaScopeOfMDT_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaScopeOfMDT_NR_1[5];
extern asn_per_constraints_t asn_PER_type_AreaScopeOfMDT_NR_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AreaScopeOfMDT_NR_H_ */
#include <asn_internal.h>
