/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#include "AreaOfInterestCellItem.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_AreaOfInterestCellItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AreaOfInterestCellItem, nGRAN_CGI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NGRAN_CGI,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nGRAN-CGI"
		},
	{ ATF_POINTER, 1, offsetof(struct AreaOfInterestCellItem, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_11905P10,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_AreaOfInterestCellItem_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_AreaOfInterestCellItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AreaOfInterestCellItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nGRAN-CGI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_AreaOfInterestCellItem_specs_1 = {
	sizeof(struct AreaOfInterestCellItem),
	offsetof(struct AreaOfInterestCellItem, _asn_ctx),
	asn_MAP_AreaOfInterestCellItem_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_AreaOfInterestCellItem_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AreaOfInterestCellItem = {
	"AreaOfInterestCellItem",
	"AreaOfInterestCellItem",
	&asn_OP_SEQUENCE,
	asn_DEF_AreaOfInterestCellItem_tags_1,
	sizeof(asn_DEF_AreaOfInterestCellItem_tags_1)
		/sizeof(asn_DEF_AreaOfInterestCellItem_tags_1[0]), /* 1 */
	asn_DEF_AreaOfInterestCellItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_AreaOfInterestCellItem_tags_1)
		/sizeof(asn_DEF_AreaOfInterestCellItem_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AreaOfInterestCellItem_1,
	2,	/* Elements count */
	&asn_SPC_AreaOfInterestCellItem_specs_1	/* Additional specs */
};

