/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_AvailableRANVisibleQoEMetrics_H_
#define	_AvailableRANVisibleQoEMetrics_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AvailableRANVisibleQoEMetrics__applicationLayerBufferLevelList {
	AvailableRANVisibleQoEMetrics__applicationLayerBufferLevelList_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_AvailableRANVisibleQoEMetrics__applicationLayerBufferLevelList;
typedef enum AvailableRANVisibleQoEMetrics__playoutDelayForMediaStartup {
	AvailableRANVisibleQoEMetrics__playoutDelayForMediaStartup_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_AvailableRANVisibleQoEMetrics__playoutDelayForMediaStartup;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* AvailableRANVisibleQoEMetrics */
typedef struct AvailableRANVisibleQoEMetrics {
	long	*applicationLayerBufferLevelList;	/* OPTIONAL */
	long	*playoutDelayForMediaStartup;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AvailableRANVisibleQoEMetrics_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_applicationLayerBufferLevelList_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_playoutDelayForMediaStartup_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_AvailableRANVisibleQoEMetrics;
extern asn_SEQUENCE_specifics_t asn_SPC_AvailableRANVisibleQoEMetrics_specs_1;
extern asn_TYPE_member_t asn_MBR_AvailableRANVisibleQoEMetrics_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AvailableRANVisibleQoEMetrics_H_ */
#include <asn_internal.h>
