/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_CEmodeBSupport_Indicator_H_
#define	_CEmodeBSupport_Indicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CEmodeBSupport_Indicator {
	CEmodeBSupport_Indicator_supported	= 0
	/*
	 * Enumeration is extensible
	 */
} e_CEmodeBSupport_Indicator;

/* CEmodeBSupport-Indicator */
typedef long	 CEmodeBSupport_Indicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CEmodeBSupport_Indicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CEmodeBSupport_Indicator;
extern const asn_INTEGER_specifics_t asn_SPC_CEmodeBSupport_Indicator_specs_1;
asn_struct_free_f CEmodeBSupport_Indicator_free;
asn_struct_print_f CEmodeBSupport_Indicator_print;
asn_constr_check_f CEmodeBSupport_Indicator_constraint;
per_type_decoder_f CEmodeBSupport_Indicator_decode_uper;
per_type_encoder_f CEmodeBSupport_Indicator_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CEmodeBSupport_Indicator_H_ */
#include <asn_internal.h>
