/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_DataForwardingResponseERABListItem_H_
#define	_DataForwardingResponseERABListItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-ID.h"
#include "UPTransportLayerInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DataForwardingResponseERABListItem */
typedef struct DataForwardingResponseERABListItem {
	E_RAB_ID_t	 e_RAB_ID;
	UPTransportLayerInformation_t	 dLForwardingUP_TNLInformation;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataForwardingResponseERABListItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataForwardingResponseERABListItem;
extern asn_SEQUENCE_specifics_t asn_SPC_DataForwardingResponseERABListItem_specs_1;
extern asn_TYPE_member_t asn_MBR_DataForwardingResponseERABListItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DataForwardingResponseERABListItem_H_ */
#include <asn_internal.h>
