/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_EUTRA_Paging_eDRX_Cycle_H_
#define	_EUTRA_Paging_eDRX_Cycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EUTRA_Paging_eDRX_Cycle {
	EUTRA_Paging_eDRX_Cycle_hfhalf	= 0,
	EUTRA_Paging_eDRX_Cycle_hf1	= 1,
	EUTRA_Paging_eDRX_Cycle_hf2	= 2,
	EUTRA_Paging_eDRX_Cycle_hf4	= 3,
	EUTRA_Paging_eDRX_Cycle_hf6	= 4,
	EUTRA_Paging_eDRX_Cycle_hf8	= 5,
	EUTRA_Paging_eDRX_Cycle_hf10	= 6,
	EUTRA_Paging_eDRX_Cycle_hf12	= 7,
	EUTRA_Paging_eDRX_Cycle_hf14	= 8,
	EUTRA_Paging_eDRX_Cycle_hf16	= 9,
	EUTRA_Paging_eDRX_Cycle_hf32	= 10,
	EUTRA_Paging_eDRX_Cycle_hf64	= 11,
	EUTRA_Paging_eDRX_Cycle_hf128	= 12,
	EUTRA_Paging_eDRX_Cycle_hf256	= 13
	/*
	 * Enumeration is extensible
	 */
} e_EUTRA_Paging_eDRX_Cycle;

/* EUTRA-Paging-eDRX-Cycle */
typedef long	 EUTRA_Paging_eDRX_Cycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EUTRA_Paging_eDRX_Cycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EUTRA_Paging_eDRX_Cycle;
extern const asn_INTEGER_specifics_t asn_SPC_EUTRA_Paging_eDRX_Cycle_specs_1;
asn_struct_free_f EUTRA_Paging_eDRX_Cycle_free;
asn_struct_print_f EUTRA_Paging_eDRX_Cycle_print;
asn_constr_check_f EUTRA_Paging_eDRX_Cycle_constraint;
per_type_decoder_f EUTRA_Paging_eDRX_Cycle_decode_uper;
per_type_encoder_f EUTRA_Paging_eDRX_Cycle_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRA_Paging_eDRX_Cycle_H_ */
#include <asn_internal.h>
