/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_ExcessPacketDelayThresholdValue_H_
#define	_ExcessPacketDelayThresholdValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExcessPacketDelayThresholdValue {
	ExcessPacketDelayThresholdValue_ms0dot25	= 0,
	ExcessPacketDelayThresholdValue_ms0dot5	= 1,
	ExcessPacketDelayThresholdValue_ms1	= 2,
	ExcessPacketDelayThresholdValue_ms2	= 3,
	ExcessPacketDelayThresholdValue_ms4	= 4,
	ExcessPacketDelayThresholdValue_ms5	= 5,
	ExcessPacketDelayThresholdValue_ms10	= 6,
	ExcessPacketDelayThresholdValue_ms20	= 7,
	ExcessPacketDelayThresholdValue_ms30	= 8,
	ExcessPacketDelayThresholdValue_ms40	= 9,
	ExcessPacketDelayThresholdValue_ms50	= 10,
	ExcessPacketDelayThresholdValue_ms60	= 11,
	ExcessPacketDelayThresholdValue_ms70	= 12,
	ExcessPacketDelayThresholdValue_ms80	= 13,
	ExcessPacketDelayThresholdValue_ms90	= 14,
	ExcessPacketDelayThresholdValue_ms100	= 15,
	ExcessPacketDelayThresholdValue_ms150	= 16,
	ExcessPacketDelayThresholdValue_ms300	= 17,
	ExcessPacketDelayThresholdValue_ms500	= 18
	/*
	 * Enumeration is extensible
	 */
} e_ExcessPacketDelayThresholdValue;

/* ExcessPacketDelayThresholdValue */
typedef long	 ExcessPacketDelayThresholdValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExcessPacketDelayThresholdValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExcessPacketDelayThresholdValue;
extern const asn_INTEGER_specifics_t asn_SPC_ExcessPacketDelayThresholdValue_specs_1;
asn_struct_free_f ExcessPacketDelayThresholdValue_free;
asn_struct_print_f ExcessPacketDelayThresholdValue_print;
asn_constr_check_f ExcessPacketDelayThresholdValue_constraint;
per_type_decoder_f ExcessPacketDelayThresholdValue_decode_uper;
per_type_encoder_f ExcessPacketDelayThresholdValue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExcessPacketDelayThresholdValue_H_ */
#include <asn_internal.h>
