/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_ExtendedReportIntervalMDT_H_
#define	_ExtendedReportIntervalMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExtendedReportIntervalMDT {
	ExtendedReportIntervalMDT_ms20480	= 0,
	ExtendedReportIntervalMDT_ms40960	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ExtendedReportIntervalMDT;

/* ExtendedReportIntervalMDT */
typedef long	 ExtendedReportIntervalMDT_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExtendedReportIntervalMDT_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExtendedReportIntervalMDT;
extern const asn_INTEGER_specifics_t asn_SPC_ExtendedReportIntervalMDT_specs_1;
asn_struct_free_f ExtendedReportIntervalMDT_free;
asn_struct_print_f ExtendedReportIntervalMDT_print;
asn_constr_check_f ExtendedReportIntervalMDT_constraint;
per_type_decoder_f ExtendedReportIntervalMDT_decode_uper;
per_type_encoder_f ExtendedReportIntervalMDT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedReportIntervalMDT_H_ */
#include <asn_internal.h>
