/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_ExtendedUEIdentityIndexValue_H_
#define	_ExtendedUEIdentityIndexValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedUEIdentityIndexValue */
typedef BIT_STRING_t	 ExtendedUEIdentityIndexValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExtendedUEIdentityIndexValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExtendedUEIdentityIndexValue;
asn_struct_free_f ExtendedUEIdentityIndexValue_free;
asn_struct_print_f ExtendedUEIdentityIndexValue_print;
asn_constr_check_f ExtendedUEIdentityIndexValue_constraint;
per_type_decoder_f ExtendedUEIdentityIndexValue_decode_uper;
per_type_encoder_f ExtendedUEIdentityIndexValue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedUEIdentityIndexValue_H_ */
#include <asn_internal.h>
