/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_FiveG_ProSePC5QoSParameters_H_
#define	_FiveG_ProSePC5QoSParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FiveGProSePC5QoSFlowList.h"
#include "BitRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* FiveG-ProSePC5QoSParameters */
typedef struct FiveG_ProSePC5QoSParameters {
	FiveGProSePC5QoSFlowList_t	 fiveGProSepc5QoSFlowList;
	BitRate_t	*fiveGProSepc5LinkAggregateBitRates;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FiveG_ProSePC5QoSParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FiveG_ProSePC5QoSParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_FiveG_ProSePC5QoSParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_FiveG_ProSePC5QoSParameters_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FiveG_ProSePC5QoSParameters_H_ */
#include <asn_internal.h>
