/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_GlobalW_AGF_ID_H_
#define	_GlobalW_AGF_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNIdentity.h"
#include "W-AGF-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* GlobalW-AGF-ID */
typedef struct GlobalW_AGF_ID {
	PLMNIdentity_t	 pLMNIdentity;
	W_AGF_ID_t	 w_AGF_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GlobalW_AGF_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GlobalW_AGF_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_GlobalW_AGF_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_GlobalW_AGF_ID_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _GlobalW_AGF_ID_H_ */
#include <asn_internal.h>
