/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_IntersystemSONInformationReply_H_
#define	_IntersystemSONInformationReply_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IntersystemSONInformationReply_PR {
	IntersystemSONInformationReply_PR_NOTHING,	/* No components present */
	IntersystemSONInformationReply_PR_nGRAN_CellActivation,
	IntersystemSONInformationReply_PR_resourceStatus,
	IntersystemSONInformationReply_PR_choice_Extensions
} IntersystemSONInformationReply_PR;

/* Forward declarations */
struct IntersystemCellActivationReply;
struct IntersystemResourceStatusReply;
struct ProtocolIE_SingleContainer;

/* IntersystemSONInformationReply */
typedef struct IntersystemSONInformationReply {
	IntersystemSONInformationReply_PR present;
	union IntersystemSONInformationReply_u {
		struct IntersystemCellActivationReply	*nGRAN_CellActivation;
		struct IntersystemResourceStatusReply	*resourceStatus;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersystemSONInformationReply_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersystemSONInformationReply;
extern asn_CHOICE_specifics_t asn_SPC_IntersystemSONInformationReply_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersystemSONInformationReply_1[3];
extern asn_per_constraints_t asn_PER_type_IntersystemSONInformationReply_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersystemSONInformationReply_H_ */
#include <asn_internal.h>
