/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_IntersystemUnnecessaryHO_H_
#define	_IntersystemUnnecessaryHO_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGRAN-CGI.h"
#include "EUTRA-CGI.h"
#include <NativeEnumerated.h>
#include "CandidateCellList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IntersystemUnnecessaryHO__earlyIRATHO {
	IntersystemUnnecessaryHO__earlyIRATHO_true	= 0,
	IntersystemUnnecessaryHO__earlyIRATHO_false	= 1
	/*
	 * Enumeration is extensible
	 */
} e_IntersystemUnnecessaryHO__earlyIRATHO;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* IntersystemUnnecessaryHO */
typedef struct IntersystemUnnecessaryHO {
	NGRAN_CGI_t	 sourcecellID;
	EUTRA_CGI_t	 targetcellID;
	long	 earlyIRATHO;
	CandidateCellList_t	 candidateCellList;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersystemUnnecessaryHO_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_earlyIRATHO_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IntersystemUnnecessaryHO;
extern asn_SEQUENCE_specifics_t asn_SPC_IntersystemUnnecessaryHO_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersystemUnnecessaryHO_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _IntersystemUnnecessaryHO_H_ */
#include <asn_internal.h>
