/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_LoggingDuration_H_
#define	_LoggingDuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoggingDuration {
	LoggingDuration_m10	= 0,
	LoggingDuration_m20	= 1,
	LoggingDuration_m40	= 2,
	LoggingDuration_m60	= 3,
	LoggingDuration_m90	= 4,
	LoggingDuration_m120	= 5
	/*
	 * Enumeration is extensible
	 */
} e_LoggingDuration;

/* LoggingDuration */
typedef long	 LoggingDuration_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LoggingDuration_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LoggingDuration;
extern const asn_INTEGER_specifics_t asn_SPC_LoggingDuration_specs_1;
asn_struct_free_f LoggingDuration_free;
asn_struct_print_f LoggingDuration_print;
asn_constr_check_f LoggingDuration_constraint;
per_type_decoder_f LoggingDuration_decode_uper;
per_type_encoder_f LoggingDuration_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoggingDuration_H_ */
#include <asn_internal.h>
