/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_M1ThresholdType_H_
#define	_M1ThresholdType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Threshold-RSRP.h"
#include "Threshold-RSRQ.h"
#include "Threshold-SINR.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum M1ThresholdType_PR {
	M1ThresholdType_PR_NOTHING,	/* No components present */
	M1ThresholdType_PR_threshold_RSRP,
	M1ThresholdType_PR_threshold_RSRQ,
	M1ThresholdType_PR_threshold_SINR,
	M1ThresholdType_PR_choice_Extensions
} M1ThresholdType_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* M1ThresholdType */
typedef struct M1ThresholdType {
	M1ThresholdType_PR present;
	union M1ThresholdType_u {
		Threshold_RSRP_t	 threshold_RSRP;
		Threshold_RSRQ_t	 threshold_RSRQ;
		Threshold_SINR_t	 threshold_SINR;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M1ThresholdType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M1ThresholdType;
extern asn_CHOICE_specifics_t asn_SPC_M1ThresholdType_specs_1;
extern asn_TYPE_member_t asn_MBR_M1ThresholdType_1[4];
extern asn_per_constraints_t asn_PER_type_M1ThresholdType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _M1ThresholdType_H_ */
#include <asn_internal.h>
