/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MBS_SessionTNLInfoNGRAN_H_
#define	_MBS_SessionTNLInfoNGRAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBS_SessionTNLInfoNGRAN_PR {
	MBS_SessionTNLInfoNGRAN_PR_NOTHING,	/* No components present */
	MBS_SessionTNLInfoNGRAN_PR_locationindependent,
	MBS_SessionTNLInfoNGRAN_PR_locationdependent,
	MBS_SessionTNLInfoNGRAN_PR_choice_Extensions
} MBS_SessionTNLInfoNGRAN_PR;

/* Forward declarations */
struct UPTransportLayerInformation;
struct MBS_SessionTNLInfoNGRANList;
struct ProtocolIE_SingleContainer;

/* MBS-SessionTNLInfoNGRAN */
typedef struct MBS_SessionTNLInfoNGRAN {
	MBS_SessionTNLInfoNGRAN_PR present;
	union MBS_SessionTNLInfoNGRAN_u {
		struct UPTransportLayerInformation	*locationindependent;
		struct MBS_SessionTNLInfoNGRANList	*locationdependent;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_SessionTNLInfoNGRAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_SessionTNLInfoNGRAN;
extern asn_CHOICE_specifics_t asn_SPC_MBS_SessionTNLInfoNGRAN_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_SessionTNLInfoNGRAN_1[3];
extern asn_per_constraints_t asn_PER_type_MBS_SessionTNLInfoNGRAN_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MBS_SessionTNLInfoNGRAN_H_ */
#include <asn_internal.h>
