/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MBS_ActiveSessionInformation_SourcetoTargetItem_H_
#define	_MBS_ActiveSessionInformation_SourcetoTargetItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MBS-SessionID.h"
#include "MBS-AreaSessionID.h"
#include "MBS-QoSFlowsToBeSetupList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBS_ServiceArea;
struct MBS_MappingandDataForwardingRequestList;
struct ProtocolExtensionContainer;

/* MBS-ActiveSessionInformation-SourcetoTargetItem */
typedef struct MBS_ActiveSessionInformation_SourcetoTargetItem {
	MBS_SessionID_t	 mBS_SessionID;
	MBS_AreaSessionID_t	*mBS_AreaSessionID;	/* OPTIONAL */
	struct MBS_ServiceArea	*mBS_ServiceArea;	/* OPTIONAL */
	MBS_QoSFlowsToBeSetupList_t	 mBS_QoSFlowsToBeSetupList;
	struct MBS_MappingandDataForwardingRequestList	*mBS_MappingandDataForwardingRequestList;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_ActiveSessionInformation_SourcetoTargetItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_ActiveSessionInformation_SourcetoTargetItem;
extern asn_SEQUENCE_specifics_t asn_SPC_MBS_ActiveSessionInformation_SourcetoTargetItem_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_ActiveSessionInformation_SourcetoTargetItem_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _MBS_ActiveSessionInformation_SourcetoTargetItem_H_ */
#include <asn_internal.h>
