/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MBS_DistributionSetupUnsuccessfulTransfer_H_
#define	_MBS_DistributionSetupUnsuccessfulTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MBS-SessionID.h"
#include "MBS-AreaSessionID.h"
#include "Cause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CriticalityDiagnostics;
struct ProtocolExtensionContainer;

/* MBS-DistributionSetupUnsuccessfulTransfer */
typedef struct MBS_DistributionSetupUnsuccessfulTransfer {
	MBS_SessionID_t	 mBS_SessionID;
	MBS_AreaSessionID_t	*mBS_AreaSessionID;	/* OPTIONAL */
	Cause_t	 cause;
	struct CriticalityDiagnostics	*criticalityDiagnostics;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_DistributionSetupUnsuccessfulTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBS_DistributionSetupUnsuccessfulTransfer;

#ifdef __cplusplus
}
#endif

#endif	/* _MBS_DistributionSetupUnsuccessfulTransfer_H_ */
#include <asn_internal.h>
