/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MDT_AlignmentInfo_H_
#define	_MDT_AlignmentInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGRANTraceID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MDT_AlignmentInfo_PR {
	MDT_AlignmentInfo_PR_NOTHING,	/* No components present */
	MDT_AlignmentInfo_PR_s_basedMDT,
	MDT_AlignmentInfo_PR_choice_Extensions
} MDT_AlignmentInfo_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* MDT-AlignmentInfo */
typedef struct MDT_AlignmentInfo {
	MDT_AlignmentInfo_PR present;
	union MDT_AlignmentInfo_u {
		NGRANTraceID_t	 s_basedMDT;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MDT_AlignmentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MDT_AlignmentInfo;
extern asn_CHOICE_specifics_t asn_SPC_MDT_AlignmentInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_MDT_AlignmentInfo_1[2];
extern asn_per_constraints_t asn_PER_type_MDT_AlignmentInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MDT_AlignmentInfo_H_ */
#include <asn_internal.h>
