/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MDT_Location_Information_H_
#define	_MDT_Location_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MDT-Location-Information */
typedef BIT_STRING_t	 MDT_Location_Information_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MDT_Location_Information_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MDT_Location_Information;
asn_struct_free_f MDT_Location_Information_free;
asn_struct_print_f MDT_Location_Information_print;
asn_constr_check_f MDT_Location_Information_constraint;
per_type_decoder_f MDT_Location_Information_decode_uper;
per_type_encoder_f MDT_Location_Information_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MDT_Location_Information_H_ */
#include <asn_internal.h>
