/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MDTModeNr_H_
#define	_MDTModeNr_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MDTModeNr_PR {
	MDTModeNr_PR_NOTHING,	/* No components present */
	MDTModeNr_PR_immediateMDTNr,
	MDTModeNr_PR_loggedMDTNr,
	MDTModeNr_PR_choice_Extensions
} MDTModeNr_PR;

/* Forward declarations */
struct ImmediateMDTNr;
struct LoggedMDTNr;
struct ProtocolIE_SingleContainer;

/* MDTModeNr */
typedef struct MDTModeNr {
	MDTModeNr_PR present;
	union MDTModeNr_u {
		struct ImmediateMDTNr	*immediateMDTNr;
		struct LoggedMDTNr	*loggedMDTNr;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MDTModeNr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MDTModeNr;
extern asn_CHOICE_specifics_t asn_SPC_MDTModeNr_specs_1;
extern asn_TYPE_member_t asn_MBR_MDTModeNr_1[3];
extern asn_per_constraints_t asn_PER_type_MDTModeNr_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MDTModeNr_H_ */
#include <asn_internal.h>
