/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_MDTPLMNModificationList_H_
#define	_MDTPLMNModificationList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNIdentity.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MDTPLMNModificationList */
typedef struct MDTPLMNModificationList {
	A_SEQUENCE_OF(PLMNIdentity_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MDTPLMNModificationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MDTPLMNModificationList;
extern asn_SET_OF_specifics_t asn_SPC_MDTPLMNModificationList_specs_1;
extern asn_TYPE_member_t asn_MBR_MDTPLMNModificationList_1[1];
extern asn_per_constraints_t asn_PER_type_MDTPLMNModificationList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MDTPLMNModificationList_H_ */
#include <asn_internal.h>
