/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NB_IoT_Paging_TimeWindow_H_
#define	_NB_IoT_Paging_TimeWindow_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NB_IoT_Paging_TimeWindow {
	NB_IoT_Paging_TimeWindow_s1	= 0,
	NB_IoT_Paging_TimeWindow_s2	= 1,
	NB_IoT_Paging_TimeWindow_s3	= 2,
	NB_IoT_Paging_TimeWindow_s4	= 3,
	NB_IoT_Paging_TimeWindow_s5	= 4,
	NB_IoT_Paging_TimeWindow_s6	= 5,
	NB_IoT_Paging_TimeWindow_s7	= 6,
	NB_IoT_Paging_TimeWindow_s8	= 7,
	NB_IoT_Paging_TimeWindow_s9	= 8,
	NB_IoT_Paging_TimeWindow_s10	= 9,
	NB_IoT_Paging_TimeWindow_s11	= 10,
	NB_IoT_Paging_TimeWindow_s12	= 11,
	NB_IoT_Paging_TimeWindow_s13	= 12,
	NB_IoT_Paging_TimeWindow_s14	= 13,
	NB_IoT_Paging_TimeWindow_s15	= 14,
	NB_IoT_Paging_TimeWindow_s16	= 15
	/*
	 * Enumeration is extensible
	 */
} e_NB_IoT_Paging_TimeWindow;

/* NB-IoT-Paging-TimeWindow */
typedef long	 NB_IoT_Paging_TimeWindow_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NB_IoT_Paging_TimeWindow_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NB_IoT_Paging_TimeWindow;
extern const asn_INTEGER_specifics_t asn_SPC_NB_IoT_Paging_TimeWindow_specs_1;
asn_struct_free_f NB_IoT_Paging_TimeWindow_free;
asn_struct_print_f NB_IoT_Paging_TimeWindow_print;
asn_constr_check_f NB_IoT_Paging_TimeWindow_constraint;
per_type_decoder_f NB_IoT_Paging_TimeWindow_decode_uper;
per_type_encoder_f NB_IoT_Paging_TimeWindow_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NB_IoT_Paging_TimeWindow_H_ */
#include <asn_internal.h>
