/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NGAPIESupportInformationResponseItem_H_
#define	_NGAPIESupportInformationResponseItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ID.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAPIESupportInformationResponseItem__ngap_ProtocolIESupportInfo {
	NGAPIESupportInformationResponseItem__ngap_ProtocolIESupportInfo_supported	= 0,
	NGAPIESupportInformationResponseItem__ngap_ProtocolIESupportInfo_not_supported	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NGAPIESupportInformationResponseItem__ngap_ProtocolIESupportInfo;
typedef enum NGAPIESupportInformationResponseItem__ngap_ProtocolIEPresenceInfo {
	NGAPIESupportInformationResponseItem__ngap_ProtocolIEPresenceInfo_present	= 0,
	NGAPIESupportInformationResponseItem__ngap_ProtocolIEPresenceInfo_not_present	= 1
	/*
	 * Enumeration is extensible
	 */
} e_NGAPIESupportInformationResponseItem__ngap_ProtocolIEPresenceInfo;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NGAPIESupportInformationResponseItem */
typedef struct NGAPIESupportInformationResponseItem {
	ProtocolIE_ID_t	 ngap_ProtocolIE_Id;
	long	 ngap_ProtocolIESupportInfo;
	long	 ngap_ProtocolIEPresenceInfo;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAPIESupportInformationResponseItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ngap_ProtocolIESupportInfo_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ngap_ProtocolIEPresenceInfo_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NGAPIESupportInformationResponseItem;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAPIESupportInformationResponseItem_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAPIESupportInformationResponseItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAPIESupportInformationResponseItem_H_ */
#include <asn_internal.h>
