/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NPN_Support_H_
#define	_NPN_Support_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NPN_Support_PR {
	NPN_Support_PR_NOTHING,	/* No components present */
	NPN_Support_PR_sNPN,
	NPN_Support_PR_choice_Extensions
} NPN_Support_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* NPN-Support */
typedef struct NPN_Support {
	NPN_Support_PR present;
	union NPN_Support_u {
		NID_t	 sNPN;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NPN_Support_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NPN_Support;
extern asn_CHOICE_specifics_t asn_SPC_NPN_Support_specs_1;
extern asn_TYPE_member_t asn_MBR_NPN_Support_1[2];
extern asn_per_constraints_t asn_PER_type_NPN_Support_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NPN_Support_H_ */
#include <asn_internal.h>
