/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NR_Paging_eDRX_Cycle_H_
#define	_NR_Paging_eDRX_Cycle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NR_Paging_eDRX_Cycle {
	NR_Paging_eDRX_Cycle_hfquarter	= 0,
	NR_Paging_eDRX_Cycle_hfhalf	= 1,
	NR_Paging_eDRX_Cycle_hf1	= 2,
	NR_Paging_eDRX_Cycle_hf2	= 3,
	NR_Paging_eDRX_Cycle_hf4	= 4,
	NR_Paging_eDRX_Cycle_hf8	= 5,
	NR_Paging_eDRX_Cycle_hf16	= 6,
	NR_Paging_eDRX_Cycle_hf32	= 7,
	NR_Paging_eDRX_Cycle_hf64	= 8,
	NR_Paging_eDRX_Cycle_hf128	= 9,
	NR_Paging_eDRX_Cycle_hf256	= 10,
	NR_Paging_eDRX_Cycle_hf512	= 11,
	NR_Paging_eDRX_Cycle_hf1024	= 12
	/*
	 * Enumeration is extensible
	 */
} e_NR_Paging_eDRX_Cycle;

/* NR-Paging-eDRX-Cycle */
typedef long	 NR_Paging_eDRX_Cycle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NR_Paging_eDRX_Cycle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NR_Paging_eDRX_Cycle;
extern const asn_INTEGER_specifics_t asn_SPC_NR_Paging_eDRX_Cycle_specs_1;
asn_struct_free_f NR_Paging_eDRX_Cycle_free;
asn_struct_print_f NR_Paging_eDRX_Cycle_print;
asn_constr_check_f NR_Paging_eDRX_Cycle_constraint;
per_type_decoder_f NR_Paging_eDRX_Cycle_decode_uper;
per_type_encoder_f NR_Paging_eDRX_Cycle_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NR_Paging_eDRX_Cycle_H_ */
#include <asn_internal.h>
