/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_NumberOfMeasurementReportingLevels_H_
#define	_NumberOfMeasurementReportingLevels_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NumberOfMeasurementReportingLevels {
	NumberOfMeasurementReportingLevels_n2	= 0,
	NumberOfMeasurementReportingLevels_n3	= 1,
	NumberOfMeasurementReportingLevels_n4	= 2,
	NumberOfMeasurementReportingLevels_n5	= 3,
	NumberOfMeasurementReportingLevels_n10	= 4
	/*
	 * Enumeration is extensible
	 */
} e_NumberOfMeasurementReportingLevels;

/* NumberOfMeasurementReportingLevels */
typedef long	 NumberOfMeasurementReportingLevels_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NumberOfMeasurementReportingLevels_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NumberOfMeasurementReportingLevels;
extern const asn_INTEGER_specifics_t asn_SPC_NumberOfMeasurementReportingLevels_specs_1;
asn_struct_free_f NumberOfMeasurementReportingLevels_free;
asn_struct_print_f NumberOfMeasurementReportingLevels_print;
asn_constr_check_f NumberOfMeasurementReportingLevels_constraint;
per_type_decoder_f NumberOfMeasurementReportingLevels_decode_uper;
per_type_encoder_f NumberOfMeasurementReportingLevels_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfMeasurementReportingLevels_H_ */
#include <asn_internal.h>
