/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_PrivacyIndicator_H_
#define	_PrivacyIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrivacyIndicator {
	PrivacyIndicator_immediate_MDT	= 0,
	PrivacyIndicator_logged_MDT	= 1
	/*
	 * Enumeration is extensible
	 */
} e_PrivacyIndicator;

/* PrivacyIndicator */
typedef long	 PrivacyIndicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PrivacyIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PrivacyIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_PrivacyIndicator_specs_1;
asn_struct_free_f PrivacyIndicator_free;
asn_struct_print_f PrivacyIndicator_print;
asn_constr_check_f PrivacyIndicator_constraint;
per_type_decoder_f PrivacyIndicator_decode_uper;
per_type_encoder_f PrivacyIndicator_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PrivacyIndicator_H_ */
#include <asn_internal.h>
