/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_QosFlowFeedbackItem_H_
#define	_QosFlowFeedbackItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QosFlowIdentifier.h"
#include "UpdateFeedback.h"
#include "ExtendedPacketDelayBudget.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* QosFlowFeedbackItem */
typedef struct QosFlowFeedbackItem {
	QosFlowIdentifier_t	 qosFlowIdentifier;
	UpdateFeedback_t	*updateFeedback;	/* OPTIONAL */
	ExtendedPacketDelayBudget_t	*cNpacketDelayBudgetDL;	/* OPTIONAL */
	ExtendedPacketDelayBudget_t	*cNpacketDelayBudgetUL;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QosFlowFeedbackItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QosFlowFeedbackItem;
extern asn_SEQUENCE_specifics_t asn_SPC_QosFlowFeedbackItem_specs_1;
extern asn_TYPE_member_t asn_MBR_QosFlowFeedbackItem_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _QosFlowFeedbackItem_H_ */
#include <asn_internal.h>
