/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_RANNodeName_H_
#define	_RANNodeName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RANNodeName */
typedef PrintableString_t	 RANNodeName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANNodeName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANNodeName;
asn_struct_free_f RANNodeName_free;
asn_struct_print_f RANNodeName_print;
asn_constr_check_f RANNodeName_constraint;
per_type_decoder_f RANNodeName_decode_uper;
per_type_encoder_f RANNodeName_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANNodeName_H_ */
#include <asn_internal.h>
