/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_ReportingSystem_H_
#define	_ReportingSystem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportingSystem_PR {
	ReportingSystem_PR_NOTHING,	/* No components present */
	ReportingSystem_PR_eUTRAN,
	ReportingSystem_PR_nGRAN,
	ReportingSystem_PR_noReporting,
	ReportingSystem_PR_choice_Extensions
} ReportingSystem_PR;

/* Forward declarations */
struct EUTRAN_ReportingSystemIEs;
struct NGRAN_ReportingSystemIEs;
struct ProtocolIE_SingleContainer;

/* ReportingSystem */
typedef struct ReportingSystem {
	ReportingSystem_PR present;
	union ReportingSystem_u {
		struct EUTRAN_ReportingSystemIEs	*eUTRAN;
		struct NGRAN_ReportingSystemIEs	*nGRAN;
		NULL_t	 noReporting;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportingSystem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportingSystem;
extern asn_CHOICE_specifics_t asn_SPC_ReportingSystem_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportingSystem_1[4];
extern asn_per_constraints_t asn_PER_type_ReportingSystem_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportingSystem_H_ */
#include <asn_internal.h>
