/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_RIMInformationTransfer_H_
#define	_RIMInformationTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TargetRANNodeID.h"
#include "SourceRANNodeID.h"
#include "RIMInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* RIMInformationTransfer */
typedef struct RIMInformationTransfer {
	TargetRANNodeID_t	 targetRANNodeID;
	SourceRANNodeID_t	 sourceRANNodeID;
	RIMInformation_t	 rIMInformation;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RIMInformationTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RIMInformationTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_RIMInformationTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_RIMInformationTransfer_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RIMInformationTransfer_H_ */
#include <asn_internal.h>
