/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_SONInformationReport_H_
#define	_SONInformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SONInformationReport_PR {
	SONInformationReport_PR_NOTHING,	/* No components present */
	SONInformationReport_PR_failureIndicationInformation,
	SONInformationReport_PR_hOReportInformation,
	SONInformationReport_PR_choice_Extensions
} SONInformationReport_PR;

/* Forward declarations */
struct FailureIndication;
struct HOReport;
struct ProtocolIE_SingleContainer;

/* SONInformationReport */
typedef struct SONInformationReport {
	SONInformationReport_PR present;
	union SONInformationReport_u {
		struct FailureIndication	*failureIndicationInformation;
		struct HOReport	*hOReportInformation;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SONInformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SONInformationReport;
extern asn_CHOICE_specifics_t asn_SPC_SONInformationReport_specs_1;
extern asn_TYPE_member_t asn_MBR_SONInformationReport_1[3];
extern asn_per_constraints_t asn_PER_type_SONInformationReport_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SONInformationReport_H_ */
#include <asn_internal.h>
