/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_UE_PagingList_H_
#define	_UE_PagingList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_PagingItem;

/* UE-PagingList */
typedef struct UE_PagingList {
	A_SEQUENCE_OF(struct UE_PagingItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_PagingList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_PagingList;
extern asn_SET_OF_specifics_t asn_SPC_UE_PagingList_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_PagingList_1[1];
extern asn_per_constraints_t asn_PER_type_UE_PagingList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_PagingList_H_ */
#include <asn_internal.h>
