/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/swthorn/git/playground/asn_paper/asn1/generated/asn1c/38414-h30_backup.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -S /home/swthorn/git/asn1c/skeletons -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-APER -no-gen-JER`
 */

#ifndef	_UserLocationInformationW_AGF_H_
#define	_UserLocationInformationW_AGF_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HFCNode-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UserLocationInformationW_AGF_PR {
	UserLocationInformationW_AGF_PR_NOTHING,	/* No components present */
	UserLocationInformationW_AGF_PR_globalLine_ID,
	UserLocationInformationW_AGF_PR_hFCNode_ID,
	UserLocationInformationW_AGF_PR_choice_Extensions
} UserLocationInformationW_AGF_PR;

/* Forward declarations */
struct GlobalLine_ID;
struct ProtocolIE_SingleContainer;

/* UserLocationInformationW-AGF */
typedef struct UserLocationInformationW_AGF {
	UserLocationInformationW_AGF_PR present;
	union UserLocationInformationW_AGF_u {
		struct GlobalLine_ID	*globalLine_ID;
		HFCNode_ID_t	 hFCNode_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserLocationInformationW_AGF_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserLocationInformationW_AGF;
extern asn_CHOICE_specifics_t asn_SPC_UserLocationInformationW_AGF_specs_1;
extern asn_TYPE_member_t asn_MBR_UserLocationInformationW_AGF_1[3];
extern asn_per_constraints_t asn_PER_type_UserLocationInformationW_AGF_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UserLocationInformationW_AGF_H_ */
#include <asn_internal.h>
